name: instahelp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  porcupine_flutter: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/someone-help-me_en_android_v2_2_0.ppn
    - assets/someone-help-me_en_ios_v2_2_0.ppn
