name: instahelp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.11.0
  firebase_ui_oauth_google: ^1.2.15
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_contact_picker: ^0.0.6
  flutter_sms:
    path: assets/flutter_sms-master
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.2.1
  just_audio: ^0.9.36
  permission_handler: ^11.0.1
  porcupine_flutter: ^3.0.1
  torch_light: ^1.0.0
  volume_controller: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/android adaptive icon foreground.png"
  adaptive_icon_background: "assets/android adaptive icon background.png"

  ios: true
  image_path: 'assets/InstaHelp icon.png'
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/get-away-from-me_en_android_v3_0_0.ppn
    - assets/get-away-from-me_en_ios_v3_0_0.ppn
    - assets/siren.wav